### ISSUE TITLE
Question about random sampling of decoder in paper

### ISSUE THREAD

**Issue by ObsisMc** [wavmark/wavmark#1]
In the paper, the decoder has an operation of random sampling but in the code, I find the random sampling is replaced with the following method:
https://github.com/wavmark/wavmark/blob/682f0afeff765a948f1f4f7c7fc21f5e63c349c3/src/wavmark/models/my_model.py#L40-L43

Is this implementation the same as the random sampling operation?

**Comment by my-yy** [comment]
Thank you for pointing this out. We found that a direct copy of the`signal_fft` could obtain a higher convergence speed; thus, random sampling was not used. We will correct this in a later version of the paper.
