### ISSUE TITLE
请问这个类库支持MP3文件的加密吗？

### ISSUE THREAD

**Issue by bison-abner** [wavmark/wavmark#11]

**Comment by my-yy** [comment]
可以在转换前先将MP3变为WAV，加密后再转换回MP3。

**Comment by bison-abner** [comment]
好的好的，感谢

**Comment by bison-abner** [comment]
您好，我还请想问个问题，您们在huggingface上所训练好的那个模型，step59000_snr39.99_pesq4.35_BERP_none0.30_mean1.81_std1.81，它的数据集是从哪里获取的呢？是使用的开源音频集还是您们团队自己收集的呢？
