### ISSUE TITLE
How to deal with time stretching attack in training

### ISSUE THREAD

**Issue by Zain-Jiang** [wavmark/wavmark#3]
Thanks for your wonderful work! 

I have a question about time stretching attack in training. After applying the time stretching operation (Increasing the speech by 1.1x), the length of signal segment is changed. Then, the length of the model_out does not match the length of the target. How to deal with it? Thank you very much for taking the time to answer my question.

**Comment by my-yy** [comment]
If the number of sample points increases after time stretching, a portion of the audio will be extracted as the model input. Conversely, if the audio becomes shorter, zeros will be added to the end of the audio.

**Comment by Zain-Jiang** [comment]
Thanks！
