### ISSUE TITLE
Could you please offer some codes for model training?

### ISSUE THREAD

**Issue by QueueRear** [wavmark/wavmark#4]
The brilliant work `WavMark` is really impressing, especially its innovated training strategies like the curriculum learning approach, shift module, and attack simulator, which are the parts I'm most interested in. While this repository seems to be a helpful tool for watermarking that only preserves the well-trained models, without those charming training procedures.

Would you consider adding modules for customed model training, like offering modules of curriculum learning approach, and attack simulator?

**Comment by my-yy** [comment]
Thank you for your interest in this work. I'm sorry, but I currently do not have permission to provide the training code for WavMark.

However, if you are interested in reproducing the results, you can refer to the following projects:

HiNet: Deep Image Hiding by Invertible Network, ICCV, 2021
[GitHub Link](https://github.com/TomTomTommi/HiNet)
The invertible network used in WavMark is referenced from this project.

DeAR: A Deep-Learning-Based Audio Re-recording Resilient Watermarking, AAAI, 2023
The training process and implementation of attack layers in WavMark are similar to those in this paper. (You can try contacting the authors of this paper to obtain DeAR's code.)

**Comment by QueueRear** [comment]
Got it! Thank you very much for your help!
