### ISSUE TITLE
pip install watermark downgrades pytorch

### ISSUE THREAD

**Issue by xvdp** [wavmark/wavmark#8]
while i applaud the project, when installed from pypi it downgrades  torch  to 1.13cu117 which messes up environments. Whatever you guys do should be as transparent as the watermark that you put. 

I have not tried installing installing from setup, just noticed this while trying TTS projects requiring your work.

Thanks.

**Comment by my-yy** [comment]
Thank you for pointing that out. The latest version has addressed this problem, just `pip install wavmark==0.0.3`.

**Comment by xvdp** [comment]
Thank you, your new version no longer clobbers previous installation.
