### ISSUE TITLE
Replicate information about the model weights on the Hub!

### ISSUE THREAD

**Issue by Vaibhavs10** [wavmark/wavmark#9]
Hi wavmark team,

I'm VB; I lead the advocacy efforts for Audio at Hugging Face. Thanks for your contribution and for releasing your weights on the Hugging Face Hub (https://huggingface.co/M4869/WavMark).

It'd be great if you could replicate the GitHub's README over to WavMark's model card as well. This will help in it's discovery and also would lead to greater visibility of the model as well.

Please do feel free to let me know if you need any support with this!

Cheers,
VB

**Comment by my-yy** [comment]
Thanks for your suggestion, the relevant page has been updated :-)
